### ISSUE TITLE
Icons need attention

### ISSUE THREAD

**Issue by markallisongit** [markallisongit/handcash-chrome#7]
- Firefox icon does not display correctly in the browser.
- Search results in chrome extensions web store not showing nicely.

**Comment by WorldLanguages** [comment]
For no. 2 you will have to go to the legacy Chrome Extension Dashboard (not the beta one with Material Design), find this extension and search the part to upload an icon. You can use the same one that you specified on manifest.json.

**Comment by markallisongit** [comment]
Asking on SO https://stackoverflow.com/questions/53957191/how-to-get-my-icon-to-display-in-my-firefox-addon

**Comment by markallisongit** [comment]
Fixed
